# Generated by Django 4.2.23 on 2025-07-20 20:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(blank=True, max_length=50, verbose_name='nombres')),
                ('pais', models.CharField(blank=True, max_length=30, verbose_name='Pais')),
                ('pasaporte', models.CharField(blank=True, max_length=50, verbose_name='Pasaporte')),
                ('edad', models.IntegerField(blank=True, null=True)),
                ('apelativo', models.CharField(blank=True, max_length=10, verbose_name='Apelativo')),
                ('email', models.EmailField(blank=True, max_length=50, verbose_name='Email')),
            ],
        ),
        migrations.CreateModel(
            name='Empleado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(blank=True, max_length=50, verbose_name='nombres')),
                ('pais', models.CharField(blank=True, max_length=30, verbose_name='Pais')),
                ('pasaporte', models.CharField(blank=True, max_length=50, verbose_name='Pasaporte')),
                ('edad', models.IntegerField(blank=True, null=True)),
                ('apelativo', models.CharField(blank=True, max_length=10, verbose_name='Apelativo')),
                ('empleo', models.CharField(blank=True, max_length=50, verbose_name='Empleo')),
            ],
        ),
        migrations.AddConstraint(
            model_name='empleado',
            constraint=models.CheckConstraint(check=models.Q(('edad__gte', 18)), name='empleado_edad_mayor_18'),
        ),
        migrations.AddConstraint(
            model_name='cliente',
            constraint=models.CheckConstraint(check=models.Q(('edad__gte', 18)), name='cliente_edad_mayor_18'),
        ),
    ]
